### ISSUE TITLE
fix header logo

### ISSUE THREAD

**Issue by allaway** [nf-osi/NF_data_curator#12]
Header logo is difficult to see - i guess the options are - 1) to pick a lighter color scheme (preferably a color from the NF Data Portal Palette), 2) to drop the logo on a white/light background (Stockard may have this already if you ask!), or 3) both of the above!

**Comment by allaway** [comment]
actually, this and #13 should probably also be defined in `www/config.json`, not in the body of the app like it currently is

**Comment by kthrog** [comment]
Going to look into how to remove what I think is a hardcoded setting, but currently, the only header (skin) colors accepted are blue, black, purple, green, red, yellow. 

From the log error I got when attempting to use a hex value for skin [here](https://github.com/nf-osi/NF_data_curator/blob/develop/app.R#L31): 
`Error in match.arg(skin) :
  'arg' should be one of “blue”, “black”, “purple”, “green”, “red”, “yellow”`

**Comment by kthrog** [comment]
For now, I have changed the header color to 'blue' (as close as I could get to portal logo colors, I think) and I'm using a portal logo with a white background, as suggested. See changes here:
https://shiny.synapse.org/users/rallaway/NF_data_curator_staging/ 
Once done making a few more style changes, will PR.

**Comment by allaway** [comment]
ah, interesting, i think we need to use CSS to change the colors beyond the presets (https://stackoverflow.com/questions/50467136/how-to-create-custom-shinydashboard-skin/50467293)

**Comment by kthrog** [comment]
that makes sense! I think that should be a quick fix, but I'm going to save that for after I experiment with the schema a bit more.
