### ISSUE TITLE
Enhance workflow to deploy automatically to staging app whenever data model changes

### ISSUE THREAD

**Issue by anngvu** [nf-osi/NF_data_curator#122]
Currently, the [workflow gets and sets the specified data model as part of deployment](https://github.com/nf-osi/NF_data_curator/blob/develop/.github/workflows/shinyapps_deploy.yml#L63-L69). This means that data model changes means redeployment, usually manually by @allaway to `staging` first by [updating `download_url`](https://github.com/nf-osi/NF_data_curator/blob/develop/schematic_config.yml#L22).

What if a release from https://github.com/nf-osi/nf-metadata-dictionary/tree/main/ automatically makes the change to `download_url` to deploy `staging`? Once user testing of `staging` app looks good, pulling changes into `main` will deploy to production as usual.

This requires:
1. nf-osi/nf-metadata-dictionary has a workflow that sends a message to this repo on event type `released` which includes data about the new release (version, download location).
2. nf-osi/NF_data_curator has a [repository_dispatch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch)-based workflow to receive event of type `released`  and commits the new version update to the config in `staging` branch, which will trigger `shinyapps_deploy` to deploy `staging` app.
3. A token may need to be set up so that nf-osi/nf-metadata-dictionary has scope to dispatch nf-osi/NF_data_curator.

Note:
Some changes in the data model do require additional changes to the DCA front-end (maybe 5% of the time?), e.g. new template also needs editing the [config.json](https://github.com/nf-osi/NF_data_curator/blob/develop/www/config.json)), so would need additional human commit for this _after_ `download_url` is updated automatically.

**Comment by allaway** [comment]
this is a great idea!
