### ISSUE TITLE
Shiny deploy fails with new configuration expectations

### ISSUE THREAD

**Issue by anngvu** [nf-osi/NF_data_curator#144]
**Describe the bug**
It looks like shiny deploy is expecting different config parameters and [now fails](https://github.com/nf-osi/NF_data_curator/actions/runs/3192457279/jobs/5209954724). We reference the model via  `model.input.download_url`, not `model.input.repo`.

```
config <- yaml::yaml.load_file("schematic_config.yml");
system(sprintf("echo MODEL_REPO=%s >> $GITHUB_ENV", config$model$input$repo));
Error in system(sprintf("echo MODEL_REPO=%s >> $GITHUB_ENV", config$model$input$repo)) : 
  non-empty character argument expected
Execution halted
Error: Process completed with exit code 1.
```

@allaway Is it safe to try to update this line to `repo` to use the new shiny deploy workflow?

**Comment by allaway** [comment]
I'm on my phone at the moment but it looks like this is just the develop branch, right? If so, I am waiting for an upstream change that is backwards compatible with the older config files. I'll take a closer look when I get home!

**Comment by anngvu** [comment]
Yes, this is just for develop. Was just looking at this file change: https://github.com/nf-osi/NF_data_curator/commit/605c82469d2bdc440fa3d53f35bc438d83639ee8#diff-5c0719296c8d398fa56ddc451d923ab39844d3ca179e8eb4c5d7debf8101d5b7

**Comment by anngvu** [comment]
I think this is another one of those instances where backwards-compatibility should have been prioritized...

**Comment by allaway** [comment]
Yeah, I think the DCA and schematic releases are slightly out of sync. The next DCA release to `main` should include changes that will make this backwards compatible.

**Comment by allaway** [comment]
Actually, I just checked and it seems like the PR (https://github.com/Sage-Bionetworks/data_curator/pull/411) has made it into `main` (https://github.com/Sage-Bionetworks/data_curator/pull/410)

**Comment by anngvu** [comment]
OK, looks like deployment works again. :tada:
