### ISSUE TITLE
Workflow update: Upgrade schematic to new version using service token auth only

### ISSUE THREAD

**Issue by anngvu** [nf-osi/NF_data_curator#154]
According to the D&T sprint review today, Google Sheets is removing support for current default authentication method (relying on OOB), so we'll need to switch to using service account token only. "Some time in January" all apps are required to "reinstall" schematic. 

For us, this should be as simple as changing `SCHEMATIC_PIN`. 
The workflow should also clean up a couple of lines as e.g. we won't need `token.pickle` anymore:
https://github.com/nf-osi/NF_data_curator/blob/develop/.github/workflows/custom_shinyapps_deploy%20.yml#L86

**Comment by allaway** [comment]
Hey @anngvu  - I didn't learn about this change till today in the D&T sprint review. Apparently, OOB is going to stop working Jan 31. Is there any chance you would be able to fit these changes in sometime before then? I could do it when I get back but that's cutting it a bit close, and it seems like you have a better grasp of the required changes than I do :)

**Comment by anngvu** [comment]
Yep, adding it to sprint starting next week.
