### ISSUE TITLE
Document important NF-specific changes compared to upstream

### ISSUE THREAD

**Issue by anngvu** [nf-osi/NF_data_curator#157]
When we pull from upstream, there are a number of merge conflicts where we have to make sure to keep some NF-specific customization. Documentation of these differences will help out the other maintainers and developers of the app.

- Can use it as a checklist to make sure we don't forget what we need to keep when syncing and resolving merge conflicts with upstream.
- If FAIR team continues development of a multi-tenant app (with one DCA interface to rule them all) that includes NF, we need to give them a clear list of things they will need to reconcile. 
- This documentation can also be informative of places where a better design is needed so that customization is easier, e.g. instead of something being hard-coded here, it should be read from a config variable.

**Comment by allaway** [comment]
Notes here:

- [ ] make this change to server.R to pull in all folders from the portal fileview (`folder_df <- syn_tableQuery(sprintf("select name, id from %s where type = 'folder' and projectId = '%s'", config$main_fileview, projectID))$asDataFrame()`)  https://github.com/nf-osi/NF_data_curator/blob/4c11ec33cae47565a8fb7db80c340152d8726fec/server.R#L164
- [ ] these associateMetadataWithFiles parameters must be set: `        manifest_record_type = "entity",
        restrict_manifest = FALSE,
        useSchemaLabel = FALSE,
        hideBlanks = TRUE`
- [ ] this getModelManifest parameter must be set: `useAnnotations = T`

**Comment by anngvu** [comment]
More:

Currently, `syn_tableQuery` etc. use function aliases defined in separate file and imported in `server.R` 
https://github.com/nf-osi/NF_data_curator/blob/fdea5ca2f5c7eb9aa3513cd310332ee441c7fe43/server.R#L27-L29

Upstream, sourcing moved to `global.R` and looks like aliases no longer sourced (file has also been removed, we still have it on our end):

https://github.com/nf-osi/NF_data_curator/blob/900dfd768d9794dcb3d57e31c75e59b5bea7a286/global.R#L99-L109
