### ISSUE TITLE
Deploy staging branch of upstream main after internal infra setup

### ISSUE THREAD

**Issue by anngvu** [nf-osi/NF_data_curator#164]
This will be as if we were setting up DCA for the very first time. The plan is to return to "official" version of schematic. We start with clean code from upstream and splice back in **_just_** what we need. This gives us a clean start and makes it much easier to see the NF configuration applied top of the basic DCA. There is a lot of dead code that was removed upstream that was never removed in our version -- see https://github.com/nf-osi/NF_data_curator/issues/157#issuecomment-1411312845 -- that this now takes care of. 

Dependent on:
- Internal setup of [NFINT-878](https://sagebionetworks.jira.com/browse/NFINT-878) (making sure we have contentType=dataset).

Code comparisons:
- (vs upstream) https://github.com/Sage-Bionetworks/data_curator/compare/main...nf-osi:NF_data_curator:staging. 
- (vs production -- this is not useful) https://github.com/nf-osi/NF_data_curator/compare/production...nf-osi:NF_data_curator:staging?expand=1

UI/UX comparisons for production vs staging:
- Compare load speed 
- Compare selection menu and functionality

Then:
- Once sufficiently tested, make this branch the real new `staging` (what is now currently `develop`).
- After user testing, in **Settings** > change Default branch to `staging`
- Change `production` to something else
- Create new `production` from `staging`

Related issues/resources: 
- https://github.com/nf-osi/NF_data_curator/issues/157

**Comment by anngvu** [comment]
@allaway @jaybee84 @cconrad8 : The current https://sagebio.shinyapps.io/NF_data_curator-staging/ is deployed from https://github.com/nf-osi/NF_data_curator/tree/staging. It should functionally feel and be nearly the same as production, though basically ~all the customizations~ customizations related to querying the fileview have been discarded.

The projects where you'll notice differences are:
| Project            | Name    | Notes |
| -------------------| ----------- | --------- |
| syn4939902 | The Johns Hopkins NF1 Biospecimen Repository | More selective over what's surfaced, less overwhelming -- only folders under Raw Data will show up (which helps a lot because that avoids all the "NF-OSI Processed Data" directories showing up).
| syn5698493   | Synodos NF1 Low Grade Glioma      | Project does not quite fit into framework
| syn7239560   | Evotec Drug Target Research                | Project does not quite fit into framework
| syn4939874   | pNF Cell Line Characterization Studies | Project does not quite fit into framework
| syn11672851 | Drug-Target Explorer                              | Project does not quite fit into framework
| syn28545963 | Schwannomatosis Open Research Collaborative      | Project does not quite fit into framework

**Comment by anngvu** [comment]
@allaway I think you're the only one who can do code review, everyone is helping mainly with UI-based testing. Let me know if things look good enough for me to make this the default branch, i.e. the new `staging`.

**Comment by jaybee84** [comment]
While doing user testing on the staging site I am still seeing high latency of startup and then an error `An error has occurred
Unable to connect to worker after 60.00 seconds; startup took too long. Contact the author for more information.`
Any idea why I see this ?

**Comment by anngvu** [comment]
@jaybee84 You should refresh the page if you see this. Shinyapps has slow start-up sometimes. On the refresh the container should be ready.

Update: I'll look at the settings, I already adjusted memory size, but there might be other things that help.

**Comment by jaybee84** [comment]
Thanks @anngvu refreshing helped! It would be great to not encounter it though.. hope your additional adjustments will resolve this.

When I select the JHU Biobank project, I see a few folders from the `NF-OSI processed data` folder pop up like `2-001-Blood` etc (see screenshot)
<img width="1792" alt="Screen Shot 2023-04-20 at 12 34 10 PM" src="https://user-images.githubusercontent.com/17917521/233470562-679f89cf-88b9-457c-a8cb-d0019408cfda.png">

Is this expected? I was only expecting to see `Raw Data` folders on there, so was a bit surprised :)

**Comment by cconrad8** [comment]
@anngvu the staging one loaded faster for me!

**Comment by anngvu** [comment]
@cconrad8 That's promising, though we probably need larger sample size.
@jaybee84 Hmm, yeah, I thought this worked as expected at some point. Will check out the commit before I started splicing back in custom code.

**Comment by anngvu** [comment]
Summary of what we see so far

Comparisons:
- This version seems to load faster, but can't say that it's statistically significant.
- In the selection UI, I think it's working now that one sees only folders which have `contentType=dataset` annotation. For old/current projects, we have recursively applied this to folders under Raw Data to retain the **same behavior as before for "backwards compatibility"** and bc it's too much work to go through each project's nested folders and figure out which ones should be dataset folders vs. not. For new projects, `contentType=dataset` will be applied selectively.

**Comment by allaway** [comment]
Code looks good to me! 

I can't say that I notice a difference in responsiveness, but just having the more restricted folders is great. 

One possible issue: 

What about newer old studies like this one: https://www.synapse.org/#!Synapse:syn36528589/wiki/619195

They only have a Raw Data folder right now, so that's the only folder where contentType='dataset'. However, we expect that they would have multiple datasets to add to this project, and of different data types, which will cause validation issues if they try to fill out different types of manifests for the same parent Raw Data folder. There are a lot of projects that are like this. How should we handle these?

**Comment by anngvu** [comment]
Yeah, that's an interesting case. So it looks like it works if I use a validation schema that says "this entity has annotation contentType=dataset if it is folder but name is not 'Raw Data'". So any folder under Raw Data is selectable, but not Raw Data itself. I think that will help. I will update the validation schema in a PR.

**Comment by cconrad8** [comment]
@anngvu @allaway @jaybee84 I'm seeing this this 60 second error again more and more - anyone else have an idea what it is? opening this thread again

**Comment by allaway** [comment]
Hmm, I am not sure. I have been meaning to re-check if the new DCA is ready
to go for us/has resolved the issues we had in testing. I'll take a look
today
