### ISSUE TITLE
set up new google account credentials

### ISSUE THREAD

**Issue by allaway** [nf-osi/NF_data_curator#22]
We now have an NF service account to support this data curator app (thanks @BrunoGrandePhD and @ahayden!) - currently every manifest that's being created is getting shoved into my google drive. 

need to 
-authenticate app using these new credentials
-add details to README.md describing this and how to get access to service acct

**Comment by BrunoGrandePhD** [comment]
For posterity, here's a (Sage-accessible) JIRA ticket for this service account: 
https://sagebionetworks.jira.com/browse/IT-989

**Comment by allaway** [comment]
Thanks!!

**Comment by kthrog** [comment]
@allaway Just wanted to check in on what's outstanding in this ticket. Is it just adding the access details to the README? I believe the rest is done, right?

**Comment by allaway** [comment]
Yes, I think that is correct!

**Comment by anngvu** [comment]
I believe this was resolved around Iteration 10 when we had to replace auth mechanism anyway. See https://github.com/nf-osi/NF_data_curator/pull/159
