### ISSUE TITLE
proposed attribute changes in schema

### ISSUE THREAD

**Issue by kthrog** [nf-osi/NF_data_curator#24]
Make these changes in the schema after first changing in the fileview; research more thoroughly, too.

- [ ] runtype -> isPairedEnd (per [GDC](https://docs.gdc.cancer.gov/Data_Dictionary/viewer/#?view=table-definition-view&id=read_group&anchor=is_paired_end))
- [ ] nucleicAcidSource -> ____?

**Comment by allaway** [comment]
I just added nucleicAcidSource to the schemas - it was missing in most places. Not sure how that intersects with this ticket (maybe we can ignore that change for now)?

**Comment by allaway** [comment]
Closing this as won't do, as there's no clear reason to do this right now.
