### ISSUE TITLE
add initiative to schema

### ISSUE THREAD

**Issue by allaway** [nf-osi/NF_data_curator#29]
**Describe the bug**
"consortium" is now "initiative" - this should be changed in the schema so that we stop generating manifests with consortium.

**Comment by allaway** [comment]
Transferring to the NF Data Curator repo because we already have schema issues there. Maybe should just reserve this repo issues for technical problems with schematic (although in that case they'd likely need to go in the root repo anyway).

**Comment by kthrog** [comment]
Now done in the Google sheet; will need to update schema in app (but won't do until tomorrow at annotation happy hour). 

Also will soon need to make some adjustments based on new initiatives + descriptions established for portal feature.

Also will be removing this to another schema, per issue #30

**Comment by kthrog** [comment]
Done, but also now irrelevant due to closing issues #23 and #30.
