### ISSUE TITLE
Add more tissue types

### ISSUE THREAD

**Issue by kthrog** [nf-osi/NF_data_curator#42]
For now, at least the following:

- `cerebral cortex`
- `sciatic nerve`

And add `skin`, but as a value under `organ`.

Potentially use this full ontology later on: https://www.ebi.ac.uk/ols/ontologies/bto

**Comment by allaway** [comment]
Skin already exists under organ - but for some reason organ wasn't showing up on these manifests. I added this into all of the manifests. 

I also added these terms using the definitions you provided. Thanks! 

If the staging app looks good, feel free to merge the schematic `develop` branch into `main` to finalize these additions! 
https://github.com/nf-osi/schematic/pull/34
