### ISSUE TITLE
value of readLength and readDepth?

### ISSUE THREAD

**Issue by allaway** [nf-osi/NF_data_curator#49]
**Describe the issue with the metadata**

 eadLength and readDepth annotations are somewhat burdensome to collect and input - particularly for readDepth, and also ambiguous (are we talking about estimated values from the platform, or actual in practice values?) 

In addition, a tool like Picard `CollectWgsMetrics` can calculate metrics like this. Therefore, we might be able to drop these values and use that to collect other values that make us approach MINSEQE compliance (http://fged.org/projects/minseqe/).

**List alternative**
Suggest remove. 

**Additional comments**
@jaybee84 I think you may have suggested readDepth, so I am wondering if perhaps I am missing something here. Is there a good reason collect this data when it can be obtained by analyzing the file itself?

**Comment by jaybee84** [comment]
The suggestion stemmed from a personal experience few months ago: An external researcher wanted to find out if they would be able to use some RNAseq files from one of our NF researchers and integrate them into the analysis they intended to do. The readLength and readDepth were major determining factors for them in trying to decide whether to download the datafiles or not.

**Comment by allaway** [comment]
Thanks for clarifying! As per our discussion, let's close and revisit if these annotations become an issue in the future.
