### ISSUE TITLE
nf1/nf2 genotype values do not play well with google/excel

### ISSUE THREAD

**Issue by allaway** [nf-osi/NF_data_curator#52]
**Describe the issue with the metadata**
the +/+ and -/- values throw issues with excel as they are interpreted as errors

**List alternative**
* We could escape the values for sheets/excel with `'` - eg `'+/+`, but then they would show up with a ' in synapse because it does not understand that as an escape. 

* We could change to plus/plus, plus/minus, minus/minus, which is an alright solution, but this is not how it would be commonly written. 

* We could change to WT (wild-type, no mutation) and then allow people to type in the explicit mutation using the hgvs standard: http://varnomen.hgvs.org/

This last one is most explicit, but will be nearly impossible to validate without purpose-built tools to do so.

**Comment by kthrog** [comment]
Thank you filing this, @allaway -- I've been meaning to every time I see it!

**Comment by allaway** [comment]
This was resolved by someone upstream, not sure who, but the latest version of schematic does not have issues with this. Hopefully we can integrate this version of schematic into the front end soon!

**Comment by allaway** [comment]
Resolved a while back.
