### ISSUE TITLE
Files uploaded to Synapse Files section (and not to a folder) aren't currently accessible for annotation

### ISSUE THREAD

**Issue by kthrog** [nf-osi/NF_data_curator#63]
**Describe the bug**
If an investigator uploads a single file into the top-level Files section (i.e., not into an Analysis, Milestone Reports, or Raw Data folder) of their Synapse project, this file is essentially un-annotatable in the current configuration of the app, as it will not display as a folder. We may want to keep things this way, but I wanted to note it, in case it becomes problematic again; it's also something we should note in documentation, if we intend to keep it this way.

This came up yesterday, when an investigator thought a file was in their Analysis folder, but it was actually just in Files, and we were unable to annotate. I didn't figure out the issue until after, so at the time, it manifested as not being able to pull in the file to the template in Data Curator.

**To Reproduce**
1. From the app, go to the 'Select Your Dataset' tab. 
2. Choose '[Neurofibromatosis Demo](https://www.synapse.org/#!Synapse:syn22410511/files/)' as your project.
3. Note that [this file](https://www.synapse.org/#!Synapse:syn24991698) is not available from the 'Folder' dropdown.
4. See "error" -- or rather, potentially confusing behavior for users.

**Expected behavior**
To be fair, it's labeled _Folder_, so to some extent, the behavior _is_ expected. I just wonder if it's what users will expect, when attempting to annotate a file not yet placed in a Folder, but in the Files section of their project.

**Screenshots**
<img width="1727" alt="image" src="https://user-images.githubusercontent.com/43977698/109192415-06c92f00-774c-11eb-9112-722e1a0c49a0.png">
For example, in the screenshot above, mydrugscreeningdata1.csv wouldn't be annotatable in the current configuration of the app, until moved to a folder.

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: Firefox
 - Version: 85

**Additional context**

**Comment by allaway** [comment]
I think that we should document that they have to put their files in one of the three folders, or a subfolder of those. We could hackily add this to the front end app so that projectIds show up in the folder menu as well, but I'm not sure off the top of my head if annotation retrieval and storage would work out of the box or if we'd run into issues.

**Comment by kthrog** [comment]
Good to know! I think for the most part, organizing files in folder, by data type and annotation 'batch', seems to be the most sensible way for people to do things anyway; so I'll just make a note to add this to our documentation (if it isn't already covered in the HTAN docs).

**Comment by allaway** [comment]
Closing - investigators need to organize their data following the template.
