### ISSUE TITLE
Add Danio rerio to species

### ISSUE THREAD

**Issue by kthrog** [nf-osi/NF_data_curator#67]
**List the new value**
Value: `Danio rerio`
Key: species

**Provide definition and source for the new value**
Definition: Zebrafish
Source url: https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=7955
Cite as: NCBI:txid7955

**Are there similar but not-quite-right values?**
Please list if applicable.

**Additional comments**
We have incoming GFF studies that use zebrafish.

**Comment by allaway** [comment]
Done!
