### ISSUE TITLE
Add [nii] to [fileFormat]

### ISSUE THREAD

**Issue by jaybee84** [nf-osi/NF_data_curator#93]
**List the new value**
Value: `nii`

Using [OLS](https://www.ebi.ac.uk/ols/index) or a similar resource, please find a standard term that fits your needs. OLS-listed NCIT and OBI dictionaries are preferred sources. Non-OLS sources of ground truth for specific items such as ONCOTREE for cancer types, or GEO for platform definitions are also appropriate. 

**Provide definition and source for the new value**
Definition:
Source url: https://nifti.nimh.nih.gov/nifti-1/

**Are there similar but not-quite-right values?**
Please list if applicable.

**Additional comments**

**Comment by allaway** [comment]
Added to schema csv, will update json-ld.
