### ISSUE TITLE
Add [mask] to [dataType]

### ISSUE THREAD

**Issue by jaybee84** [nf-osi/NF_data_curator#94]
**List the new value**
Value: `mask`

Using [OLS](https://www.ebi.ac.uk/ols/index) or a similar resource, please find a standard term that fits your needs. OLS-listed NCIT and OBI dictionaries are preferred sources. Non-OLS sources of ground truth for specific items such as ONCOTREE for cancer types, or GEO for platform definitions are also appropriate. 

**Provide definition and source for the new value**
Definition:
Source url:

**Are there similar but not-quite-right values?**
Please list if applicable.

**Additional comments**

**Comment by jaybee84** [comment]
could not find appropriate ontology source :(

**Comment by allaway** [comment]
How about this? https://www.ebi.ac.uk/ols/ontologies/dicom/terms?iri=http%3A%2F%2Fdicom.nema.org%2Fresources%2Fontology%2FDCM%2F121321

I'd probably truncate it to "mask image"

**Comment by allaway** [comment]
I added this to the schema csv (https://docs.google.com/spreadsheets/d/1tHG_g-Z0FW1oXyHZz8ASbzyWWEzETwZTksk-eZv8eRg/edit#gid=0&range=A159). Let me know what you think of this term and if you agree it's sufficient i'll build a new jsonld file and push it to the app. thanks!
